# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

orbs:
  win: circleci/windows@4.1

executors:
  psp-executor:
    docker: 
      - image: pspdev/pspdev:latest
  
  vita-executor:
    docker: 
      - image: iridescentrose/psvitadev:latest

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  linux:
    machine:
      image: ubuntu-2204:2022.10.2
    
    steps:
      - checkout
      - run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libasound2-dev libjack-jackd2-dev oss4-dev libpulse-dev libsdl2-dev libsdl2-mixer-dev
          git submodule update --init --recursive --remote
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j5
          cd ..
          mkdir CrossCraft
          mkdir CrossCraft/resourcepacks
          cp resourcepacks/default.zip CrossCraft/resourcepacks/default.zip
          mv build/CrossCraft-SurvivalTest CrossCraft/CrossCraft-SurvivalTest
          strip ./CrossCraft/CrossCraft-SurvivalTest
          chmod +x ./CrossCraft/CrossCraft-SurvivalTest
          zip -r CCST-Linux.zip CrossCraft
#      - store_artifacts:
#          path: CCST-Linux.zip


  mac:
    macos:
      xcode: 14.1.0
    
    steps:
      - checkout
      - run: |
          curl -fL --retry 3 --max-time 300 -o cmake.tar.gz https://github.com/Kitware/CMake/releases/download/v3.20.3/cmake-3.20.3-macos-universal.tar.gz
          mkdir cmake
          tar -xf cmake.tar.gz --strip 3 -C cmake
          rm cmake.tar.gz
      - run: |
          git submodule update --init --recursive --remote
          mkdir -p build
          cd build
          ../cmake/bin/cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j5
          cd ..
          mkdir CrossCraft
          mkdir CrossCraft/resourcepacks
          cp resourcepacks/default.zip CrossCraft/resourcepacks/default.zip
          mv build/CrossCraft-SurvivalTest CrossCraft/CrossCraft-SurvivalTest
          chmod +x ./CrossCraft/CrossCraft-SurvivalTest
          zip -r CCST-Mac.zip CrossCraft
#      - store_artifacts:
#          path: CCST-Mac.zip

  psp:
    executor: psp-executor

    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: "apk add bash cmake git gmp mpc1 mpfr4 make zip"
      - run: |
          git config --global --add safe.directory /__w/CrossCraft-SurvivalTest/CrossCraft-SurvivalTest
          git submodule update --init --recursive --remote
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$PSPDEV/psp/share/pspdev.cmake ..
          make -j5
          cd ..
          mkdir CrossCraft
          mkdir -p CrossCraft/resourcepacks/default/
          mv build/EBOOT.PBP CrossCraft/EBOOT.PBP
          mv build/CrossCraft-SurvivalTest.prx CrossCraft/CrossCraft-SurvivalTest.prx
          unzip resourcepacks/default.zip -d CrossCraft/resourcepacks/default/
          zip -r CCST-PSP.zip CrossCraft
#      - store_artifacts:
#          path: CCST-PSP.zip

  psvita:
    executor: vita-executor

    steps:
      - checkout
      - run: |
          export VITASDK=/usr/local/vitasdk
          export PATH=$VITASDK/bin:$PATH
          sudo apt-get install --yes --force-yes zip unzip
          git config --global --add safe.directory /__w/CrossCraft-SurvivalTest/CrossCraft-SurvivalTest
          git submodule update --init --recursive --remote
          mkdir -p build
          cd build
          cmake -DVITA=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake ..
          make -j5
          cd ..
          mkdir CrossCraft
          mv build/CrossCraft-SurvivalTest.vpk CrossCraft/CrossCraft-SurvivalTest.vpk
          mkdir -p CrossCraft/CrossCraft-ST/resourcepacks/default/
          unzip resourcepacks/default.zip -d CrossCraft/CrossCraft-ST/resourcepacks/default/
          zip -r CCST-Vita.zip CrossCraft
#      - store_artifacts:
#          path: CCST-Vita.zip

workflows:
  st4-workflow:
    when: 
      equal: [ "Trigger", << pipeline.parameters.GHA_Action >> ]
    jobs:
      - linux
#      - mac
      - psp
      - psvita
