name: CrossCraft

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI
        id: Trigger
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.TK_PERSONAL }}


  Windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          git submodule update --init --recursive
          vcpkg install sdl2 --triplet x64-windows
          vcpkg install sdl2-mixer --triplet x64-windows
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -A x64 .
          copy ext/zconf.h ext/zlib/zconf.h
          cmake --build . --config Release
          move Release\CrossCraft-SurvivalTest.exe CrossCraft-SurvivalTest.exe
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: CrossCraft-Windows
          path: |
            CrossCraft-SurvivalTest.exe
            zlib.dll
            OpenAL32.dll
            resourcepacks\
            LICENSE
            README.md
            config.cfg
